/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 13, 18, 65 };

// (before - mean) / scale
const float ei_classifier_anom_scale[4] = { 1.781950431478971, 2.726860365430457, 2.3434915262883194, 44.781645693253644 };
const float ei_classifier_anom_mean[4] = { 1.7230910123029441, 3.0216795945736465, 0.41466007446400843, 34.30072099440768 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[6] = {
	{ ( float[4] ) { -0.31742843985557556, 0.4629786014556885, 0.724876344203949, -0.3305529057979584 }, 1.1219230875643849 },
	{ ( float[4] ) { -0.43830057978630066, -0.9691361784934998, -0.3329111337661743, -0.6668133735656738 }, 0.9809880293437349 },
	{ ( float[4] ) { 1.6373578310012817, 0.9741498231887817, 0.7770875096321106, 1.6154766082763672 }, 1.2189162670798113 },
	{ ( float[4] ) { -0.9612178802490234, -1.1043652296066284, -1.7043321132659912, -0.7638852596282959 }, 0.45239724542712034 },
	{ ( float[4] ) { 1.9733068943023682, 1.6416950225830078, 0.8934050798416138, 2.21290922164917 }, 1.1614644434844805 },
	{ ( float[4] ) { 0.2410355806350708, 1.5384489297866821, 0.8732764720916748, 0.4782246947288513 }, 1.2395526881822532 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
